apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: senders-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Hetzner's default class. Change for other clusters.
  storageClassName: hcloud-volumes
